import os
import numpy as np
import random
import cv2
import tools.VisualQuestion as VQ
import json_pkl
##################################################################################################3

'''
Test the acurracyt of the images generated in the Im2Sim2Im_from_image_2_code_2_im.py
By matching them to the original real image in multi choice test using either human or vlm (see figure (Image_Matching_Scheme.jpg) or paper) 

'''


################################Run  image to image matching test ###########################################################################################

def run_test_nat2sim_im(main_dir,
                     num_choices,
                     max_question=100,
                     display=False,
                     results_dir="",
                     outdir="",
                     single_image=True,
                     model="gpt-5-mini",
                     greyscale=False):
    results={"correct":0,"wrong":0,"fail":0, "fail_generation":0}
#-----------------Create file structure------------------------------------------
    if greyscale and not single_image: exit("Error greyscal only supported with single image")
    im_data={}
    for dr in os.listdir(main_dir):
         path=main_dir+"//"+dr
         if not (os.path.exists(path+"//image.jpg") and os.path.exists(path+"//origin.jpg")): continue
         im_data[dr]={"REAL":path+"//origin.jpg","SIM":path+"//image.jpg"}




#-------------------run test-----------------------------------------------------------------------
    all_grps = list(im_data.keys())

    for  n_qst,pos_grp in enumerate(all_grps):
        if n_qst>max_question:break
        correct_indx=np.random.randint(num_choices)+1
        correct_choice  = "SIM" + str(correct_indx)
        used_groups = [pos_grp]
        test_images = {"REAL":im_data[pos_grp]['REAL']}
        if not os.path.exists(im_data[pos_grp]['REAL']) or not os.path.exists(im_data[pos_grp]['SIM']):
            results["fail_generation"]+=1

    #--------------------------Select Simulated images-------------------------------------------------------------

        options=[]

        for ii in range(1,num_choices+1):
            options.append("SIM"+str(ii))
            if ii==correct_indx:
                grp = pos_grp
            else:
                while (True):
                    grp = random.sample(all_grps, 1)[0]
                    if grp not in used_groups:
                        used_groups.append(grp)
                        break
            test_images["SIM"+str(ii)]=im_data[grp]["SIM"]

    #-------------------------Create text---------------------------------------------------------------------------
        txt = (
                '\nYou are given an image of a real-world pattern, labeled as ***Real***.' 
                "\nYou are also provided with several simulated images, each generated by a different process and labeled as: " + str(options) + ". "
                "\nExactly one of these simulated images was creating by modelling the process produced the ***Real*** image. "
                "\nFind out which one is it."                                                                                                   
                "\nReturn your response in strict JSON format:"
                '{\n'
                '\n"answer": "<label of the simulated image that created by modelling the system in the real image>,'
                '\nexplanation": "<explaining your answer>'
                "}")
        if greyscale: txt+="\n(to make the test more challanging all images were converted to greyscale)"


#--------------------------------------------------------------------------------------------------------------------------------
        # --------------Unify images (optional)----------------------------------------------
        if single_image:
            im_path = ""
            if len(outdir) > 0:
                if not os.path.exists(outdir): os.mkdir(outdir)
                im_path = outdir + "//" + str(n_qst) + ".jpg"
                json_pkl.save_json(test_images, outdir + "//" + str(n_qst) + ".json")
            im, test_images = VQ.unify_image(data=test_images, num_columns=6, labels=["REAL","SIM"],#options,#["reference", "test"],
                                             out_file=im_path, disp=False)
            if greyscale:
                grayscale_image = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
                cv2.imwrite(im_path,grayscale_image)
        #-----------------------Get image matching from human or VLM---------------------------------------------------------------------------------------------------------------
        outcome= "fail"
        print(txt)
        for i in range(4):
         #  ans=F3.get_response_image_json(text=txt,img_path=test_images, model="gpt-5")
           ans = VQ.get_response_image_txt_json(text=txt, img_path=test_images, model=model)
           print(ans)
           if 'answer' in ans and ans['answer'] in options:
               if ans['answer']==correct_choice:
                   outcome= "correct"
               else:
                   outcome= "wrong"
               break
        print(outcome)

        results[outcome] += 1

        print(results)
        # ***************************Display and save **********************************************************
        # ================== save============
        if len(results_dir) > 0:# and (outcome == "wrong" or outcome == "fail"):
            if not os.path.exists(results_dir): os.mkdir(results_dir)
            spec_er_dir = os.path.join(results_dir, pos_grp+"_"+outcome)
            if not os.path.exists(spec_er_dir): os.mkdir(spec_er_dir)
            for ky in test_images:
                if ky == correct_choice:
                    cv2.imwrite(spec_er_dir + "//" + ky + "correct.jpg", cv2.imread(test_images[ky]))
                elif ky == ans["answer"]:
                    cv2.imwrite(spec_er_dir + "//" + ky + "choice.jpg", cv2.imread(test_images[ky]))
                else:
                    cv2.imwrite(spec_er_dir + "//" + ky + ".jpg", cv2.imread(test_images[ky]))
            with open(spec_er_dir + "//data.txt", "w") as fl:
                fl.write(pos_grp + "\n" + str(ans) + "\ncorrect " + correct_choice)
        #-----------------------------------------------------------------------------------
        # display
        if display:
            for ky in test_images:
                if ky == correct_choice:
                    cv2.imshow(ky + "correct", cv2.imread(test_images[ky]))
                else:
                    cv2.imshow(ky + "  " + grp, cv2.imread(test_images[ky]))
                    print(grp)
            cv2.waitKey()
        # =*******************************************************
        #--------------------Calculate average accuracy-----------------------------------------------------------------

    results["accuracy"] = results["correct"]/(results["wrong"]+results["fail"]+results["correct"])
    return results

##############################################################################################################
############################################main ###########################################################################################
# ----------------------------- __main__ -----------------------------

if __name__ == "__main__":
    # >>>>> EDIT PATH BELOW TO YOUR DATA ROOT <<<<<
    main_dir = r"..//Image2Sim2Im_output//" # input dir (the folder generate when you run Im2Sim2Im_from_image_2_code_2_im.py)
    out_dir = r"..//Matching_test_results//" # Outdir where the results will be save
    model = "human"#"gpt-5"# "human" # which model will be used for the matching (could also be human)
    num_choices=8 # number of choices in the multi choice question (for human cant be more then 10, or the more then the number of models in the main_Dir)
    run_test_nat2sim_im(main_dir,
                        num_choices=num_choices,
                        max_question=100,
                        display=False,
                        results_dir=out_dir,
                        outdir=out_dir,
                        single_image=True,
                        model=model,
                        greyscale=False)
    #run_test_multi_model(main_in_dir=main_dir, main_outdir=out_dir, model="human", greyscale=False, max_questions=30, )
    #run_test_multi_model(main_in_dir=main_dir,main_outdir=out_dir,model="gpt-5",greyscale=False,  max_questions=100,)
########################## Run test with multiple models #####################################################################################################33
# def run_test_multi_model(
#         main_in_dir,
#         main_outdir,
#         max_questions=100,
#         num_choices=10,
#         single_img=True,
#         model="gpt-5",
#         skip_exist=True,
#         greyscale=False
#
# ):
#     if not os.path.exists(main_outdir):os.mkdir(main_outdir)
#
#
#     model_simple_name = model.replace(".", "").replace(" ", "").replace("-", "_").replace("/", "_").replace(r"\\",
#                                                                                                                 r"_")
#     for dr in os.listdir(main_in_dir):
#             in_dir = main_in_dir + "//" +dr + "//"
#             if skip_exist and os.path.exists(main_outdir + "//" + dr + "_" + model_simple_name + ".pkl"): continue
#             if not os.path.isdir(in_dir):  continue
#             results_dir = out_dir+"//"+dr+"_results//"
#
#             stats = run_test_nat2sim_im(
#                                  main_dir=in_dir,
#                                  max_question=max_questions,
#                                  num_choices=num_choices,
#                                  display=False,
#                                  results_dir=results_dir,
#                                  model=model,
#                                  single_image=single_img,
#
#                                  outdir=main_outdir + "//" + model_simple_name,
#                                  greyscale=greyscale
#             )
#
#             json_pkl.save_json(stats,main_outdir+"//" + dr + "_" + model_simple_name+".json")
#             json_pkl.save_pkl(stats, main_outdir + "//" + dr + "_" + model_simple_name + ".pkl")
#             print(main_outdir+"//"+model_simple_name)




